// <auto-generated />
namespace CollegeManagementCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _20200222 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20200222));
        
        string IMigrationMetadata.Id
        {
            get { return "202002221917424_20200222"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
